package compose

import (
	"fmt"
	"sort"
	"strings"

	"github.com/vivek7405/pilots/hostd/internal/api"
)

// The compose fragment a database is added as.
//
// # Why a recipe rather than a managed service
//
// A managed database is somebody else operating your database. We are not
// offering that, and `docs/honesty.md` says so. What a recipe offers instead is
// the thing that actually makes a managed database useful nine times out of
// ten: the correct configuration, written down, with the durability decision
// made and explained rather than left as a default nobody chose.
//
// The output is a compose fragment because that is what the platform already
// runs. A database added this way is an ordinary service: the same rollout, the
// same health gate, the same volume, the same snapshots. Nothing about it is a
// second system.
//
// # Why hostd generates it and the CLI fetches it
//
// The CLI cannot import this package -- Go's `internal` visibility -- and
// copying the recipes into it would be a second copy of a contract that has to
// stay in step with the planner. The generator lives here and both clients ask
// for it. `pilot add` is always followed by a deploy that needs the fleet
// anyway, so the round trip costs nothing, and the PASSWORD is generated by the
// client and never crosses the wire.
//
// # The two Postgres modes, and why the default is the one it is
//
// `wal-archive` keeps the data directory on local disk and ships write-ahead
// log segments to a volume every sixty seconds. Recovery point objective: sixty
// seconds. Every commit is a local disk write.
//
// `durable-volume` puts the data directory itself on the volume. Recovery point
// objective: zero. Every commit is an object-storage round trip.
//
// The default is wal-archive, because sixty seconds of exposure on a machine
// that has not crashed is a better trade for most applications than putting
// object-storage latency in the commit path of every write. An application that
// genuinely cannot lose a minute asks for the other one, which is the right way
// round: the expensive choice should be chosen rather than inherited.

// Recipe is everything needed to add one database to a project.
type Recipe struct {
	Engine string `json:"engine"`
	// Mode is "wal-archive" or "durable-volume" for Postgres, and
	// "durable-volume" for every other engine: none of them has an equivalent
	// of WAL archiving that we would be right to configure for them.
	Mode string `json:"mode"`
	// Service is the compose service block, ready to splice into a file.
	Service map[string]any `json:"service"`
	// Volumes are the named volumes it declares.
	Volumes map[string]struct{} `json:"volumes"`
	// Files are extra files the fragment needs, by path relative to the
	// project root. Anything ending .sh is written executable.
	Files map[string]string `json:"files,omitempty"`
	// SecretNames are the secrets the caller must generate and store. Named
	// rather than carried: the password is made on the caller's machine and
	// never travels.
	SecretNames []string `json:"secret_names"`
	// ConnVar is the environment variable an application reads to reach this
	// database, and URLTemplate is its value with PASSWORD standing in for the
	// generated secret.
	ConnVar     string `json:"conn_var"`
	URLTemplate string `json:"url_template"`
	// Statement is the one-line explanation of the durability trade this mode
	// makes. Printed by `pilot add` and shown in the dashboard, because a
	// durability decision the operator did not read is a decision they did not
	// make.
	Statement string `json:"statement"`
}

// Engines are the databases a recipe exists for.
//
// Four, and no more until each has been run: a recipe that has not been
// deployed is a guess about somebody's production database.
var Engines = []string{"postgres", "mysql", "redis", "mongo"}

// ValidEngine reports whether a recipe exists for this engine.
func ValidEngine(engine string) bool {
	for _, e := range Engines {
		if e == engine {
			return true
		}
	}
	return false
}

// Modes a recipe can be generated in.
const (
	ModeWALArchive    = "wal-archive"
	ModeDurableVolume = "durable-volume"
)

// Generate builds the fragment for one database.
//
// name defaults to the engine, so `pilot add postgres` gives a service called
// postgres reachable at postgres.internal. pool applies to Postgres only.
func Generate(engine, name, mode string, pool bool) (*Recipe, error) {
	if !ValidEngine(engine) {
		return nil, fmt.Errorf("compose: no recipe for %q; there are recipes for %s",
			engine, strings.Join(Engines, ", "))
	}
	if name == "" {
		name = engine
	}
	if err := api.ValidateLabel(name); err != nil {
		return nil, fmt.Errorf("compose: %q is not a usable service name: %w", name, err)
	}

	switch engine {
	case "postgres":
		if mode == "" {
			mode = ModeWALArchive
		}
		if mode != ModeWALArchive && mode != ModeDurableVolume {
			return nil, fmt.Errorf("compose: postgres mode %q is neither %s nor %s",
				mode, ModeWALArchive, ModeDurableVolume)
		}
		return postgresRecipe(name, mode, pool), nil
	default:
		if mode != "" && mode != ModeDurableVolume {
			return nil, fmt.Errorf("compose: %s has only the %s mode; "+
				"no other engine here has a WAL archive we would be right to configure",
				engine, ModeDurableVolume)
		}
		return simpleRecipe(engine, name), nil
	}
}

// healthcheck is the shape every engine's block uses, so a database is held to
// the same gate a web service is: a deploy that cannot reach the database is a
// deploy that does not go through.
func healthcheck(test ...string) map[string]any {
	return map[string]any{
		"test":     append([]string{"CMD-SHELL"}, test...),
		"interval": "10s",
		"timeout":  "5s",
		"retries":  5,
	}
}

// pilotsBlock is the x-pilots extension every recipe carries.
//
// private: true on all of them. A database serves its port to peers over
// .internal and has nothing to answer on the public app port, so an address
// would only be a URL that times out.
func pilotsBlock(engine string, durable bool) map[string]any {
	return map[string]any{
		"durable_volume": durable,
		"private":        true,
		"engine":         engine,
		// A daily snapshot kept for a week, plus a month of weeklies. Set by
		// default rather than left to the operator: a database with no backup
		// policy is the single most common way a self-hosted platform loses
		// somebody's data, and the cost of the default is a few clones.
		"snapshots": map[string]any{
			"cron": "@daily", "keep_daily": 7, "keep_weekly": 4,
		},
	}
}

func postgresRecipe(name, mode string, pool bool) *Recipe {
	port := "5432"
	env := map[string]any{
		"POSTGRES_PASSWORD": "secret://postgres_password",
		"PGDATA":            "/var/lib/postgresql/data",
	}
	r := &Recipe{
		Engine: "postgres", Mode: mode,
		Volumes:     map[string]struct{}{},
		Files:       map[string]string{},
		SecretNames: []string{"postgres_password"},
		ConnVar:     "DATABASE_URL",
	}

	if mode == ModeDurableVolume {
		r.Service = map[string]any{
			"image":       "postgres:17",
			"environment": env,
			"volumes":     []string{"pgdata:/var/lib/postgresql/data"},
			"ports":       []string{port},
			"healthcheck": healthcheck("pg_isready -U postgres"),
			"x-pilots":    pilotsBlock("postgres", true),
		}
		r.Volumes["pgdata"] = struct{}{}
		r.Statement = "The data directory is on the volume, so a committed write is " +
			"already in object storage: nothing is lost if the host dies. Every commit " +
			"pays an object-storage round trip."
	} else {
		r.Service = map[string]any{
			"build": "./.pilots/" + name,
			// A LIST rather than a string. The archive command contains spaces
			// and a `&&`, and a string would be re-split by whatever runs it.
			"command": []string{
				"postgres",
				"-c", "archive_mode=on",
				"-c", "archive_timeout=60",
				"-c", "archive_command=test ! -f /archive/wal/%f && cp %p /archive/wal/%f",
			},
			"environment": env,
			"volumes":     []string{"pgarchive:/archive"},
			"ports":       []string{port},
			"healthcheck": healthcheck("pg_isready -U postgres"),
			"x-pilots":    pilotsBlock("postgres", false),
		}
		// A weekly base backup, so point-in-time recovery never has to replay
		// more than a week of write-ahead log. Without it the archive grows
		// without bound and a recovery to last Tuesday replays from the day the
		// database was created.
		r.Service["x-pilots"].(map[string]any)["schedules"] = []map[string]any{
			{"cron": "@weekly", "cmd": "/usr/local/bin/pilot-pg-basebackup"},
		}
		r.Volumes["pgarchive"] = struct{}{}
		r.Files[".pilots/"+name+"/Dockerfile"] = postgresDockerfile
		r.Files[".pilots/"+name+"/10-base-backup.sh"] = postgresBaseBackup
		r.Files[".pilots/"+name+"/pilot-pg-basebackup"] = postgresPeriodicBackup
		r.Files[".pilots/"+name+"/pilot-entrypoint.sh"] = postgresEntrypoint
		r.Statement = "The data directory is local and write-ahead log segments ship to " +
			"the volume every 60 seconds, so a host failure can lose up to a minute of " +
			"writes. Commits do not wait for object storage. Use --durable-volume if a " +
			"minute is too much."
	}

	if pool {
		// The connection string points at the POOLER, because that is what an
		// application should be talking to: Postgres spends a process per
		// connection, and an application that opens one per request exhausts
		// it long before it exhausts the machine. The direct address is
		// published too, for the migrations and admin tools that need it.
		r.ConnVar = "DATABASE_URL"
		r.URLTemplate = "postgres://postgres:PASSWORD@" + name + ".internal:6432/postgres"
		r.Statement += " Connections go through pgbouncer on 6432; " +
			name + ".internal:5432 is the direct address."
	} else {
		r.URLTemplate = "postgres://postgres:PASSWORD@" + name + ".internal:" + port + "/postgres"
	}
	return r
}

// simpleRecipe is every engine whose only durable mode is "put the data
// directory on the volume".
//
// One function rather than three, because they differ only in the image, the
// port, the data path, the health command and the environment -- and a
// per-engine function would invite each to drift its own way on the parts that
// should not differ at all: the x-pilots block, the snapshot policy, the
// privacy, the health-check shape.
func simpleRecipe(engine, name string) *Recipe {
	type shape struct {
		image     string
		port      string
		dataPath  string
		health    string
		env       map[string]any
		connVar   string
		urlScheme string
		secret    string
	}
	shapes := map[string]shape{
		"mysql": {
			image: "mysql:8", port: "3306", dataPath: "/var/lib/mysql",
			health: "mysqladmin ping -h 127.0.0.1 --silent",
			env: map[string]any{
				"MYSQL_ROOT_PASSWORD": "secret://mysql_password",
				"MYSQL_DATABASE":      "app",
			},
			connVar: "MYSQL_URL", urlScheme: "mysql://root:PASSWORD@", secret: "mysql_password",
		},
		"redis": {
			image: "redis:7", port: "6379", dataPath: "/data",
			health: "redis-cli -a \"$REDIS_PASSWORD\" ping",
			env: map[string]any{
				"REDIS_PASSWORD": "secret://redis_password",
			},
			connVar: "REDIS_URL", urlScheme: "redis://default:PASSWORD@", secret: "redis_password",
		},
		"mongo": {
			image: "mongo:7", port: "27017", dataPath: "/data/db",
			health: "mongosh --quiet --eval \"db.adminCommand('ping')\"",
			env: map[string]any{
				"MONGO_INITDB_ROOT_USERNAME": "root",
				"MONGO_INITDB_ROOT_PASSWORD": "secret://mongo_password",
			},
			connVar: "MONGO_URL", urlScheme: "mongodb://root:PASSWORD@", secret: "mongo_password",
		},
	}
	sh := shapes[engine]

	svc := map[string]any{
		"image":       sh.image,
		"environment": sh.env,
		"volumes":     []string{volumeNameFor(engine) + ":" + sh.dataPath},
		"ports":       []string{sh.port},
		"healthcheck": healthcheck(sh.health),
		"x-pilots":    pilotsBlock(engine, true),
	}
	if engine == "redis" {
		// Appendonly, because the default is a periodic RDB dump and a Redis
		// restarted between dumps comes back having lost whatever happened
		// since. A cache can afford that; something using Redis as a queue or a
		// lock cannot, and the recipe should not decide which this is.
		svc["command"] = []string{
			"redis-server", "--appendonly", "yes",
			"--requirepass", "$REDIS_PASSWORD",
		}
	}

	url := sh.urlScheme + name + ".internal:" + sh.port
	if engine == "mysql" {
		url += "/app"
	}
	return &Recipe{
		Engine: engine, Mode: ModeDurableVolume,
		Service:     svc,
		Volumes:     map[string]struct{}{volumeNameFor(engine): {}},
		SecretNames: []string{sh.secret},
		ConnVar:     sh.connVar,
		URLTemplate: url,
		Statement: "The data directory is on the volume, so a committed write is " +
			"already in object storage: nothing is lost if the host dies. Every write " +
			"pays an object-storage round trip.",
	}
}

// volumeNameFor is the named volume an engine's data lives in.
func volumeNameFor(engine string) string {
	switch engine {
	case "mysql":
		return "mysqldata"
	case "redis":
		return "redisdata"
	case "mongo":
		return "mongodata"
	default:
		return engine + "data"
	}
}

// SecretNamesSorted is the recipe's secrets in a stable order, so a caller
// generating them produces the same file twice.
func (r *Recipe) SecretNamesSorted() []string {
	out := append([]string(nil), r.SecretNames...)
	sort.Strings(out)
	return out
}

// URLFor is the connection string with the generated password in it.
func (r *Recipe) URLFor(password string) string {
	return strings.Replace(r.URLTemplate, "PASSWORD", password, 1)
}

// Two lines on top of the stock image.
//
// The base backup is taken by an INIT script rather than afterwards: the
// entrypoint starts its temporary server with the same `command` arguments, so
// archiving is already on when the first WAL segment is written, and a backup
// taken here is consistent with the archive that follows it. Taken afterwards,
// there is a window whose segments belong to no backup.
const postgresDockerfile = `FROM postgres:17
COPY 10-base-backup.sh /docker-entrypoint-initdb.d/
COPY pilot-pg-basebackup /usr/local/bin/pilot-pg-basebackup
COPY pilot-entrypoint.sh /usr/local/bin/pilot-entrypoint.sh
RUN chmod +x /usr/local/bin/pilot-pg-basebackup /usr/local/bin/pilot-entrypoint.sh
ENTRYPOINT ["/usr/local/bin/pilot-entrypoint.sh"]
CMD ["postgres"]
`

// Taken weekly, so a recovery never replays more than a week of write-ahead
// log, and pruned so the archive does not grow without bound.
//
// The pruning is the half that is easy to leave out and expensive to leave out.
// Keeping four bases plus every segment since the oldest of them bounds the
// archive at roughly a month; keeping every base forever bounds it at nothing,
// and the volume fills with backups of a database that has since been dropped.
//
// WAL older than the OLDEST KEPT BASE is what gets deleted -- not WAL older
// than some age. A segment older than the oldest base can never be replayed
// onto anything, and a segment newer than it might be the one a recovery needs.
const postgresPeriodicBackup = `#!/bin/sh
set -e
BASE="/archive/base/$(date -u +%Y%m%dT%H%M%SZ)"
mkdir -p /archive/wal "$BASE"
pg_basebackup -U postgres -D "$BASE" -Ft -z -X none

# Keep the newest four. Sorted by name, which is the timestamp, so this needs
# no stat and cannot disagree with the directory names.
KEEP=4
ls -1d /archive/base/*/ 2>/dev/null | sort -r | tail -n +$((KEEP + 1)) | while read -r old; do
  rm -rf "$old"
done

# Then every segment older than what the oldest surviving base needs. The base
# directory's own mtime is the moment it was taken, so a segment older than it
# belongs to a backup that is gone.
OLDEST=$(ls -1d /archive/base/*/ 2>/dev/null | sort | head -1)
if [ -n "$OLDEST" ]; then
  find /archive/wal -type f ! -newer "$OLDEST" -delete 2>/dev/null || true
fi
`

// The entrypoint that turns an archive into a recovery.
//
// Wraps the stock one rather than replacing it: everything about initdb, the
// temporary server and the init scripts stays exactly as the image intends, and
// this adds one branch in front of it.
//
// The branch fires only when PILOT_PG_RESTORE_TARGET is set AND the data
// directory is empty -- that second condition is what makes it safe to leave
// the variable set. A restore that ran against a populated directory would
// throw away a working database to replay an old one.
//
// pg_isready passes only after the recovery promotes, so the release health
// gate IS the restore gate: a recovery that cannot reach its target never
// becomes the running release.
const postgresEntrypoint = `#!/bin/sh
set -e

if [ -n "$PILOT_PG_RESTORE_TARGET" ] && [ -z "$(ls -A "$PGDATA" 2>/dev/null)" ]; then
  echo "pilot: restoring to $PILOT_PG_RESTORE_TARGET"

  # The newest base taken AT OR BEFORE the target. A later one contains data
  # from after the moment being recovered to, which cannot be replayed
  # backwards.
  WANT=$(echo "$PILOT_PG_RESTORE_TARGET" | tr -d ':-' | cut -c1-15)
  BASE=""
  for candidate in $(ls -1d /archive/base/*/ 2>/dev/null | sort); do
    stamp=$(basename "$candidate")
    if [ "$PILOT_PG_RESTORE_TARGET" = "latest" ] || [ "$stamp" \< "$WANT" ] || [ "$stamp" = "$WANT" ]; then
      BASE="$candidate"
    fi
  done
  if [ -z "$BASE" ]; then
    echo "pilot: no base backup at or before $PILOT_PG_RESTORE_TARGET" >&2
    exit 1
  fi
  echo "pilot: restoring from $BASE"

  mkdir -p "$PGDATA"
  for tarball in "$BASE"*.tar.gz; do
    [ -f "$tarball" ] || continue
    tar -xzf "$tarball" -C "$PGDATA"
  done
  chmod 700 "$PGDATA"

  {
    echo "restore_command = 'cp /archive/wal/%f \"%p\"'"
    echo "recovery_target_action = 'promote'"
    if [ "$PILOT_PG_RESTORE_TARGET" != "latest" ]; then
      echo "recovery_target_time = '$PILOT_PG_RESTORE_TARGET'"
    fi
  } >> "$PGDATA/postgresql.auto.conf"

  # The signal file is what tells Postgres this is a recovery rather than a
  # crash. Without it the server starts normally on a data directory that is
  # mid-restore, which is a corrupt database that reports itself healthy.
  touch "$PGDATA/recovery.signal"
fi

# The stock entrypoint, unchanged. It skips initdb on a non-empty PGDATA, so
# the restore above simply becomes the database it starts.
exec docker-entrypoint.sh "$@"
`

const postgresBaseBackup = `#!/bin/sh
# Taken once, during initdb, into the archive volume. Point-in-time recovery is
# this backup plus every WAL segment archived after it.
#
# Timestamped, so a later backup does not overwrite the one the existing
# archive segments belong to: recovering to a moment needs the newest base
# taken BEFORE that moment, and a single directory can only answer for one.
set -e
BASE="/archive/base/$(date -u +%Y%m%dT%H%M%SZ)"
mkdir -p /archive/wal "$BASE"
pg_basebackup -U postgres -D "$BASE" -Ft -z -X none
`
