package compose

import (
	"fmt"
	"sort"
	"strings"

	"github.com/vivek7405/pilots/hostd/internal/api"
)

// The compose fragment a database is added as.
//
// # Why a recipe rather than a managed service
//
// A managed database is somebody else operating your database. We are not
// offering that, and `docs/honesty.md` says so. What a recipe offers instead is
// the thing that actually makes a managed database useful nine times out of
// ten: the correct configuration, written down, with the durability decision
// made and explained rather than left as a default nobody chose.
//
// The output is a compose fragment because that is what the platform already
// runs. A database added this way is an ordinary service: the same rollout, the
// same health gate, the same volume, the same snapshots. Nothing about it is a
// second system.
//
// # Why hostd generates it and the CLI fetches it
//
// The CLI cannot import this package -- Go's `internal` visibility -- and
// copying the recipes into it would be a second copy of a contract that has to
// stay in step with the planner. The generator lives here and both clients ask
// for it. `pilot add` is always followed by a deploy that needs the fleet
// anyway, so the round trip costs nothing, and the PASSWORD is generated by the
// client and never crosses the wire.
//
// # The two Postgres modes, and why the default is the one it is
//
// `wal-archive` keeps the data directory on local disk and ships write-ahead
// log segments to a volume every sixty seconds. Recovery point objective: sixty
// seconds. Every commit is a local disk write.
//
// `durable-volume` puts the data directory itself on the volume. Recovery point
// objective: zero. Every commit is an object-storage round trip.
//
// The default is wal-archive, because sixty seconds of exposure on a machine
// that has not crashed is a better trade for most applications than putting
// object-storage latency in the commit path of every write. An application that
// genuinely cannot lose a minute asks for the other one, which is the right way
// round: the expensive choice should be chosen rather than inherited.

// Recipe is everything needed to add one database to a project.
type Recipe struct {
	Engine string `json:"engine"`
	// Mode is "wal-archive" or "durable-volume" for Postgres, and
	// "durable-volume" for every other engine: none of them has an equivalent
	// of WAL archiving that we would be right to configure for them.
	Mode string `json:"mode"`
	// Service is the compose service block, ready to splice into a file.
	Service map[string]any `json:"service"`
	// Companions are further compose services the recipe declares, by name.
	//
	// One so far: the connection pooler. It is a SERVICE rather than something
	// bolted onto the database's own block because that is what it is -- a
	// second command over the same filesystem -- and the planner already folds
	// services that share a build context into one machine with two processes
	// (see group.go). So the pooler costs no second machine, no second image,
	// no second rollout and no new concept; it reaches Postgres over the
	// loopback of the guest they share.
	Companions map[string]map[string]any `json:"companions,omitempty"`
	// Volumes are the named volumes it declares.
	Volumes map[string]struct{} `json:"volumes"`
	// Files are extra files the fragment needs, by path relative to the
	// project root. Anything ending .sh is written executable.
	Files map[string]string `json:"files,omitempty"`
	// SecretNames are the secrets the caller must generate and store. Named
	// rather than carried: the password is made on the caller's machine and
	// never travels.
	SecretNames []string `json:"secret_names"`
	// ConnVar is the environment variable an application reads to reach this
	// database, and URLTemplate is its value with PASSWORD standing in for the
	// generated secret.
	ConnVar     string `json:"conn_var"`
	URLTemplate string `json:"url_template"`
	// DirectVar and DirectTemplate are the SECOND connection string, past the
	// pooler, set only when there is a pooler to go past.
	//
	// Both are published because transaction pooling is not a superset of a
	// direct connection: it costs LISTEN/NOTIFY, session advisory locks,
	// temporary tables and any SET that outlives a transaction. A migration
	// tool pointed at the pooler fails in ways that look like a broken
	// migration, so the address that works is named rather than left to be
	// rediscovered.
	DirectVar      string `json:"direct_var,omitempty"`
	DirectTemplate string `json:"direct_template,omitempty"`
	// Statement is the one-line explanation of the durability trade this mode
	// makes. Printed by `pilot add` and shown in the dashboard, because a
	// durability decision the operator did not read is a decision they did not
	// make.
	Statement string `json:"statement"`
}

// DirectURLFor is the connection string that goes PAST the pooler, with the
// generated password in it. Empty when this recipe has no pooler.
func (r *Recipe) DirectURLFor(password string) string {
	if r.DirectTemplate == "" {
		return ""
	}
	return strings.Replace(r.DirectTemplate, "PASSWORD", password, 1)
}

// Engines are the databases a recipe exists for.
//
// Four, and no more until each has been run: a recipe that has not been
// deployed is a guess about somebody's production database.
var Engines = []string{"postgres", "mysql", "redis", "mongo"}

// ValidEngine reports whether a recipe exists for this engine.
func ValidEngine(engine string) bool {
	for _, e := range Engines {
		if e == engine {
			return true
		}
	}
	return false
}

// Modes a recipe can be generated in.
const (
	ModeWALArchive    = "wal-archive"
	ModeDurableVolume = "durable-volume"
)

// Generate builds the fragment for one database.
//
// name defaults to the engine, so `pilot add postgres` gives a service called
// postgres reachable at postgres.internal. pool applies to Postgres only.
func Generate(engine, name, mode string, pool bool) (*Recipe, error) {
	if !ValidEngine(engine) {
		return nil, fmt.Errorf("compose: no recipe for %q; there are recipes for %s",
			engine, strings.Join(Engines, ", "))
	}
	if name == "" {
		name = engine
	}
	if err := api.ValidateLabel(name); err != nil {
		return nil, fmt.Errorf("compose: %q is not a usable service name: %w", name, err)
	}

	switch engine {
	case "postgres":
		if mode == "" {
			mode = ModeWALArchive
		}
		if mode != ModeWALArchive && mode != ModeDurableVolume {
			return nil, fmt.Errorf("compose: postgres mode %q is neither %s nor %s",
				mode, ModeWALArchive, ModeDurableVolume)
		}
		return postgresRecipe(name, mode, pool), nil
	default:
		if mode != "" && mode != ModeDurableVolume {
			return nil, fmt.Errorf("compose: %s has only the %s mode; "+
				"no other engine here has a WAL archive we would be right to configure",
				engine, ModeDurableVolume)
		}
		return simpleRecipe(engine, name), nil
	}
}

// healthcheck is the shape every engine's block uses, so a database is held to
// the same gate a web service is: a deploy that cannot reach the database is a
// deploy that does not go through.
func healthcheck(test ...string) map[string]any {
	return map[string]any{
		"test":     append([]string{"CMD-SHELL"}, test...),
		"interval": "10s",
		"timeout":  "5s",
		"retries":  5,
	}
}

// pilotsBlock is the x-pilots extension every recipe carries.
//
// private: true on all of them. A database serves its port to peers over
// .internal and has nothing to answer on the public app port, so an address
// would only be a URL that times out.
func pilotsBlock(engine string, durable bool) map[string]any {
	return map[string]any{
		"durable_volume": durable,
		"private":        true,
		"engine":         engine,
		// A daily snapshot kept for a week, plus a month of weeklies. Set by
		// default rather than left to the operator: a database with no backup
		// policy is the single most common way a self-hosted platform loses
		// somebody's data, and the cost of the default is a few clones.
		"snapshots": map[string]any{
			"cron": "@daily", "keep_daily": 7, "keep_weekly": 4,
		},
	}
}

func postgresRecipe(name, mode string, pool bool) *Recipe {
	port := "5432"
	env := map[string]any{
		"POSTGRES_PASSWORD": "secret://postgres_password",
		"PGDATA":            "/var/lib/postgresql/data",
	}
	r := &Recipe{
		Engine: "postgres", Mode: mode,
		Volumes:     map[string]struct{}{},
		Files:       map[string]string{},
		SecretNames: []string{"postgres_password"},
		ConnVar:     "DATABASE_URL",
	}

	// A database publishes NOTHING, in either mode.
	//
	// Publishing is about the router, and the router dials container port 8080.
	// A database has nothing to answer there, so a file that publishes 5432 and
	// not 8080 describes a service the router can never reach -- which the
	// planner refuses, by name, and rightly.
	//
	// Not publishing costs nothing, because it was never what made the database
	// reachable. Guest-to-guest traffic is plain IP over the mesh, so a peer
	// dials <name>.internal:5432 whether compose mentions the port or not. The
	// health gate is the `healthcheck` command, which runs inside the guest and
	// has no port in it either.
	if mode == ModeDurableVolume {
		r.Service = map[string]any{
			"image":       "postgres:17",
			"environment": env,
			"volumes":     []string{"pgdata:/var/lib/postgresql/data"},
			"healthcheck": healthcheck("pg_isready -U postgres"),
			"x-pilots":    pilotsBlock("postgres", true),
		}
		r.Volumes["pgdata"] = struct{}{}
		r.Statement = "The data directory is on the volume, so a committed write is " +
			"already in object storage: nothing is lost if the host dies. Every commit " +
			"pays an object-storage round trip."
	} else {
		r.Service = map[string]any{
			"build": "./.pilots/" + name,
			// A LIST rather than a string. The archive command contains spaces
			// and a `&&`, and a string would be re-split by whatever runs it.
			"command": []string{
				"postgres",
				"-c", "archive_mode=on",
				"-c", "archive_timeout=60",
				"-c", "archive_command=test ! -f /archive/wal/%f && cp %p /archive/wal/%f",
			},
			"environment": env,
			"volumes":     []string{"pgarchive:/archive"},
			"healthcheck": healthcheck("pg_isready -U postgres"),
			"x-pilots":    pilotsBlock("postgres", false),
		}
		// A weekly base backup, so point-in-time recovery never has to replay
		// more than a week of write-ahead log. Without it the archive grows
		// without bound and a recovery to last Tuesday replays from the day the
		// database was created.
		r.Service["x-pilots"].(map[string]any)["schedules"] = []map[string]any{
			{"cron": "@weekly", "cmd": "/usr/local/bin/pilot-pg-basebackup"},
		}
		r.Volumes["pgarchive"] = struct{}{}
		r.Files[".pilots/"+name+"/Dockerfile"] = postgresDockerfile
		r.Files[".pilots/"+name+"/10-base-backup.sh"] = postgresBaseBackup
		r.Files[".pilots/"+name+"/pilot-pg-basebackup"] = postgresPeriodicBackup
		r.Files[".pilots/"+name+"/pilot-entrypoint.sh"] = postgresEntrypoint
		r.Statement = "The data directory is local and write-ahead log segments ship to " +
			"the volume every 60 seconds, so a host failure can lose up to a minute of " +
			"writes. Commits do not wait for object storage. Use --durable-volume if a " +
			"minute is too much."
	}

	if pool {
		addPooler(r, name, env)
		// The connection string points at the POOLER, because that is what an
		// application should be talking to: Postgres spends a process per
		// connection, and an application that opens one per request exhausts
		// it long before it exhausts the machine. The direct address is
		// published too, for the migrations and admin tools that need it.
		r.ConnVar = "DATABASE_URL"
		r.URLTemplate = "postgres://postgres:PASSWORD@" + name + ".internal:6432/postgres"
		r.DirectVar = "DATABASE_URL_DIRECT"
		r.DirectTemplate = "postgres://postgres:PASSWORD@" + name + ".internal:" + port + "/postgres"
		r.Statement += " Connections go through pgbouncer on 6432 in transaction " +
			"mode; " + name + ".internal:5432 is the direct address, which is what " +
			"migrations and any session-level feature must use."
	} else {
		r.URLTemplate = "postgres://postgres:PASSWORD@" + name + ".internal:" + port + "/postgres"
	}
	return r
}

// simpleRecipe is every engine whose only durable mode is "put the data
// directory on the volume".
//
// One function rather than three, because they differ only in the image, the
// port, the data path, the health command and the environment -- and a
// per-engine function would invite each to drift its own way on the parts that
// should not differ at all: the x-pilots block, the snapshot policy, the
// privacy, the health-check shape.
func simpleRecipe(engine, name string) *Recipe {
	type shape struct {
		image     string
		port      string
		dataPath  string
		health    string
		env       map[string]any
		connVar   string
		urlScheme string
		secret    string
	}
	shapes := map[string]shape{
		"mysql": {
			image: "mysql:8", port: "3306", dataPath: "/var/lib/mysql",
			health: "mysqladmin ping -h 127.0.0.1 --silent",
			env: map[string]any{
				"MYSQL_ROOT_PASSWORD": "secret://mysql_password",
				"MYSQL_DATABASE":      "app",
			},
			connVar: "MYSQL_URL", urlScheme: "mysql://root:PASSWORD@", secret: "mysql_password",
		},
		"redis": {
			image: "redis:7", port: "6379", dataPath: "/data",
			// $$ , not $ . A single dollar is a COMPOSE variable, substituted
			// when the file is parsed, and the password is not in the
			// environment of whoever runs `pilot deploy` -- so the file failed
			// to load at all, with "unset variable REDIS_PASSWORD". Compose's
			// own escape passes a literal $ through to the guest, where the
			// variable does exist.
			health: "redis-cli -a \"$$REDIS_PASSWORD\" ping",
			env: map[string]any{
				"REDIS_PASSWORD": "secret://redis_password",
			},
			connVar: "REDIS_URL", urlScheme: "redis://default:PASSWORD@", secret: "redis_password",
		},
		"mongo": {
			image: "mongo:7", port: "27017", dataPath: "/data/db",
			health: "mongosh --quiet --eval \"db.adminCommand('ping')\"",
			env: map[string]any{
				"MONGO_INITDB_ROOT_USERNAME": "root",
				"MONGO_INITDB_ROOT_PASSWORD": "secret://mongo_password",
			},
			connVar: "MONGO_URL", urlScheme: "mongodb://root:PASSWORD@", secret: "mongo_password",
		},
	}
	sh := shapes[engine]

	svc := map[string]any{
		"image":       sh.image,
		"environment": sh.env,
		"volumes":     []string{volumeNameFor(engine) + ":" + sh.dataPath},
		"healthcheck": healthcheck(sh.health),
		"x-pilots":    pilotsBlock(engine, true),
	}
	if engine == "redis" {
		// Appendonly, because the default is a periodic RDB dump and a Redis
		// restarted between dumps comes back having lost whatever happened
		// since. A cache can afford that; something using Redis as a queue or a
		// lock cannot, and the recipe should not decide which this is.
		svc["command"] = []string{
			"redis-server", "--appendonly", "yes",
			// $$ for the same reason the healthcheck uses it: a single dollar
			// is substituted when compose PARSES the file, where the password
			// does not exist. The guest gets a literal $ and expands it itself.
			"--requirepass", "$$REDIS_PASSWORD",
		}
	}

	url := sh.urlScheme + name + ".internal:" + sh.port
	if engine == "mysql" {
		url += "/app"
	}
	return &Recipe{
		Engine: engine, Mode: ModeDurableVolume,
		Service:     svc,
		Volumes:     map[string]struct{}{volumeNameFor(engine): {}},
		SecretNames: []string{sh.secret},
		ConnVar:     sh.connVar,
		URLTemplate: url,
		Statement: "The data directory is on the volume, so a committed write is " +
			"already in object storage: nothing is lost if the host dies. Every write " +
			"pays an object-storage round trip.",
	}
}

// volumeNameFor is the named volume an engine's data lives in.
func volumeNameFor(engine string) string {
	switch engine {
	case "mysql":
		return "mysqldata"
	case "redis":
		return "redisdata"
	case "mongo":
		return "mongodata"
	default:
		return engine + "data"
	}
}

// SecretNamesSorted is the recipe's secrets in a stable order, so a caller
// generating them produces the same file twice.
func (r *Recipe) SecretNamesSorted() []string {
	out := append([]string(nil), r.SecretNames...)
	sort.Strings(out)
	return out
}

// URLFor is the connection string with the generated password in it.
func (r *Recipe) URLFor(password string) string {
	return strings.Replace(r.URLTemplate, "PASSWORD", password, 1)
}

// Two lines on top of the stock image.
//
// The base backup is taken by an INIT script rather than afterwards: the
// entrypoint starts its temporary server with the same `command` arguments, so
// archiving is already on when the first WAL segment is written, and a backup
// taken here is consistent with the archive that follows it. Taken afterwards,
// there is a window whose segments belong to no backup.
const postgresDockerfile = `FROM postgres:17
COPY 10-base-backup.sh /docker-entrypoint-initdb.d/
COPY pilot-pg-basebackup /usr/local/bin/pilot-pg-basebackup
COPY pilot-entrypoint.sh /usr/local/bin/pilot-entrypoint.sh
RUN chmod +x /usr/local/bin/pilot-pg-basebackup /usr/local/bin/pilot-entrypoint.sh
ENTRYPOINT ["/usr/local/bin/pilot-entrypoint.sh"]
CMD ["postgres"]
`

// Taken weekly, so a recovery never replays more than a week of write-ahead
// log, and pruned so the archive does not grow without bound.
//
// The pruning is the half that is easy to leave out and expensive to leave out.
// Keeping four bases plus every segment since the oldest of them bounds the
// archive at roughly a month; keeping every base forever bounds it at nothing,
// and the volume fills with backups of a database that has since been dropped.
//
// WAL older than the OLDEST KEPT BASE is what gets deleted -- not WAL older
// than some age. A segment older than the oldest base can never be replayed
// onto anything, and a segment newer than it might be the one a recovery needs.
const postgresPeriodicBackup = `#!/bin/sh
set -e
BASE="/archive/base/$(date -u +%Y%m%dT%H%M%SZ)"
mkdir -p /archive/wal "$BASE"
pg_basebackup -U postgres -D "$BASE" -Ft -z -X none

# Keep the newest four. Sorted by name, which is the timestamp, so this needs
# no stat and cannot disagree with the directory names.
KEEP=4
ls -1d /archive/base/*/ 2>/dev/null | sort -r | tail -n +$((KEEP + 1)) | while read -r old; do
  rm -rf "$old"
done

# Then every segment older than what the oldest surviving base needs. The base
# directory's own mtime is the moment it was taken, so a segment older than it
# belongs to a backup that is gone.
OLDEST=$(ls -1d /archive/base/*/ 2>/dev/null | sort | head -1)
if [ -n "$OLDEST" ]; then
  find /archive/wal -type f ! -newer "$OLDEST" -delete 2>/dev/null || true
fi
`

// The entrypoint that turns an archive into a recovery.
//
// Wraps the stock one rather than replacing it: everything about initdb, the
// temporary server and the init scripts stays exactly as the image intends, and
// this adds one branch in front of it.
//
// The branch fires only when PILOT_PG_RESTORE_TARGET is set AND the data
// directory is empty -- that second condition is what makes it safe to leave
// the variable set. A restore that ran against a populated directory would
// throw away a working database to replay an old one.
//
// pg_isready passes only after the recovery promotes, so the release health
// gate IS the restore gate: a recovery that cannot reach its target never
// becomes the running release.
const postgresEntrypoint = `#!/bin/sh
set -e

if [ -n "$PILOT_PG_RESTORE_TARGET" ] && [ -z "$(ls -A "$PGDATA" 2>/dev/null)" ]; then
  echo "pilot: restoring to $PILOT_PG_RESTORE_TARGET"

  # The newest base taken AT OR BEFORE the target. A later one contains data
  # from after the moment being recovered to, which cannot be replayed
  # backwards.
  WANT=$(echo "$PILOT_PG_RESTORE_TARGET" | tr -d ':-' | cut -c1-15)
  BASE=""
  for candidate in $(ls -1d /archive/base/*/ 2>/dev/null | sort); do
    stamp=$(basename "$candidate")
    if [ "$PILOT_PG_RESTORE_TARGET" = "latest" ] || [ "$stamp" \< "$WANT" ] || [ "$stamp" = "$WANT" ]; then
      BASE="$candidate"
    fi
  done
  if [ -z "$BASE" ]; then
    echo "pilot: no base backup at or before $PILOT_PG_RESTORE_TARGET" >&2
    exit 1
  fi
  echo "pilot: restoring from $BASE"

  mkdir -p "$PGDATA"
  for tarball in "$BASE"*.tar.gz; do
    [ -f "$tarball" ] || continue
    tar -xzf "$tarball" -C "$PGDATA"
  done
  chmod 700 "$PGDATA"

  {
    echo "restore_command = 'cp /archive/wal/%f \"%p\"'"
    echo "recovery_target_action = 'promote'"
    if [ "$PILOT_PG_RESTORE_TARGET" != "latest" ]; then
      echo "recovery_target_time = '$PILOT_PG_RESTORE_TARGET'"
    fi
  } >> "$PGDATA/postgresql.auto.conf"

  # The signal file is what tells Postgres this is a recovery rather than a
  # crash. Without it the server starts normally on a data directory that is
  # mid-restore, which is a corrupt database that reports itself healthy.
  touch "$PGDATA/recovery.signal"
fi

# The stock entrypoint, unchanged. It skips initdb on a non-empty PGDATA, so
# the restore above simply becomes the database it starts.
exec docker-entrypoint.sh "$@"
`

const postgresBaseBackup = `#!/bin/sh
# Taken once, during initdb, into the archive volume. Point-in-time recovery is
# this backup plus every WAL segment archived after it.
#
# Timestamped, so a later backup does not overwrite the one the existing
# archive segments belong to: recovering to a moment needs the newest base
# taken BEFORE that moment, and a single directory can only answer for one.
set -e
BASE="/archive/base/$(date -u +%Y%m%dT%H%M%SZ)"
mkdir -p /archive/wal "$BASE"
pg_basebackup -U postgres -D "$BASE" -Ft -z -X none
`

// addPooler turns a Postgres recipe into a database with a pooler beside it.
//
// # Why a second PROCESS and not a second machine
//
// A pooler is only worth having next to the database. Put it on its own
// machine and every query pays a second network hop to save a connection, and
// the pooler becomes a thing that can be down while the database is up. Here
// it shares the guest, reaches Postgres over 127.0.0.1, and lives and dies
// with it -- which is what an operator already assumes about it.
//
// The planner does this without a new concept: services that share a build
// context become ONE machine with several processes (group.go). So the pooler
// is written as an ordinary compose service that happens to build from the
// same directory, and everything downstream -- the rollout, the health gate,
// the snapshot, the volume -- is unchanged.
//
// # Why the database keeps the machine's port
//
// Only one process owns a machine's published port, and it must be the one the
// health gate asks about. `pg_isready` on the database is the honest answer to
// "is this service up"; a pooler that answers while the database behind it is
// still recovering would let a broken release through. The pooler needs no
// published port to be reachable: guest-to-guest traffic is plain IP on the
// mesh, so 6432 answers on <name>.internal whether compose mentions it or not.
//
// # Why transaction mode
//
// Session mode pools almost nothing: a client that holds its connection holds
// a server connection with it, which is the problem. Transaction mode is the
// one that turns hundreds of client connections into a handful of server ones.
// It costs the session-level features -- LISTEN/NOTIFY, session advisory
// locks, temporary tables, SET that outlives a transaction -- and that cost is
// why the direct address stays published and is named in the statement rather
// than hidden.
func addPooler(r *Recipe, name string, env map[string]any) {
	// Pooling needs a build context, because the grouping rule is "same build
	// context and same Dockerfile means one machine". In durable-volume mode
	// the recipe otherwise runs the stock image, so it gains a Dockerfile that
	// is that image plus pgbouncer.
	if _, built := r.Service["build"]; !built {
		delete(r.Service, "image")
		r.Service["build"] = "./.pilots/" + name
		r.Files[".pilots/"+name+"/Dockerfile"] = postgresPlainDockerfile
	} else {
		r.Files[".pilots/"+name+"/Dockerfile"] = postgresPooledDockerfile
	}
	r.Files[".pilots/"+name+"/pilot-pgbouncer.sh"] = pgbouncerStart
	r.Files[".pilots/"+name+"/pilot-role.sh"] = roleDispatch
	r.Files[".pilots/"+name+"/pilot-patroni.sh"] = patroniStart
	r.Files[".pilots/"+name+"/pilot-haproxy.sh"] = haproxyStart
	r.Files[".pilots/"+name+"/pilot-etcd.sh"] = etcdStart
	r.Files[".pilots/"+name+"/pilot-pg-flush"] = walFlush

	// The pooler's environment is the database's, so it reads the same
	// password from the same secret. One secret, not two that have to agree.
	if r.Companions == nil {
		r.Companions = map[string]map[string]any{}
	}
	r.Companions[name+"-pool"] = map[string]any{
		"build":       "./.pilots/" + name,
		"command":     []string{"/usr/local/bin/pilot-pgbouncer.sh"},
		"environment": env,
		// Ordered, not raced: pgbouncer with no database behind it accepts
		// connections and fails them, which looks like a broken application
		// rather than a database that has not finished starting.
		"depends_on": []string{name},
	}
}

// haLayer is Patroni, etcd and HAProxy, in every Postgres image this writes.
//
// In every image, including the ones that will never run a cluster, because the
// alternative is that turning high availability on is a REBUILD: a new release,
// a new image, and a window in which the old nodes and the new ones are not the
// same software. One image with three unused binaries is a layer that caches
// once; a conversion with a build in the middle of it is a failure mode.
//
// Pinned by major version rather than floating, so an image rebuilt next year
// is the same cluster software and not a surprise upgrade nobody asked for.
const haLayer = `RUN apt-get update && apt-get install -y --no-install-recommends \
  pgbouncer patroni etcd-server etcd-client haproxy python3-etcd3 curl \
  && rm -rf /var/lib/apt/lists/*
COPY pilot-pgbouncer.sh /usr/local/bin/pilot-pgbouncer.sh
COPY pilot-role.sh /usr/local/bin/pilot-role.sh
COPY pilot-patroni.sh /usr/local/bin/pilot-patroni.sh
COPY pilot-haproxy.sh /usr/local/bin/pilot-haproxy.sh
COPY pilot-etcd.sh /usr/local/bin/pilot-etcd.sh
COPY pilot-pg-flush /usr/local/bin/pilot-pg-flush
RUN chmod +x /usr/local/bin/pilot-*
`

// postgresPlainDockerfile is the stock image plus the pooler, for the mode that
// otherwise needs no image of its own.
const postgresPlainDockerfile = `FROM postgres:17
` + haLayer

// postgresPooledDockerfile is the wal-archive image plus the pooler.
const postgresPooledDockerfile = postgresDockerfile + haLayer

// The pooler's configuration is written at START, not baked into the image.
//
// It contains the database password, and an image is a thing that gets pushed,
// cached, shared and inspected. Writing the file at start keeps the secret in
// the machine that already holds it and nowhere else, and means rotating the
// password is a restart rather than a rebuild.
//
// The userlist holds the password in the clear at mode 0600 inside the guest,
// and auth is scram-sha-256 anyway: pgbouncer derives the SCRAM exchange from
// the plaintext it holds, so nothing crosses the wire in the clear in either
// direction -- not from the client to the pooler, and not from the pooler to
// Postgres.
const pgbouncerStart = `#!/bin/sh
set -e

mkdir -p /etc/pgbouncer /var/log/pgbouncer /var/run/pgbouncer

# 0600 before the password is in it, not after: a file written world-readable
# and then chmodded is world-readable for however long that takes.
umask 077
cat > /etc/pgbouncer/userlist.txt <<EOF
"postgres" "$POSTGRES_PASSWORD"
EOF

cat > /etc/pgbouncer/pgbouncer.ini <<'EOF'
[databases]
* = host=127.0.0.1 port=5432

[pgbouncer]
listen_addr = *
listen_port = 6432
auth_type = scram-sha-256
auth_file = /etc/pgbouncer/userlist.txt

# Transaction mode is the one that pools: a client connection holds a server
# connection only for the length of a transaction.
pool_mode = transaction

# default_pool_size is per user/database pair, and is the number that actually
# bounds Postgres. 20 against the stock max_connections of 100 leaves headroom
# for the direct address, for pilot metrics, and for a replica.
default_pool_size = 20
reserve_pool_size = 5
reserve_pool_timeout = 3

# max_client_conn is what the pooler is FOR: the number of application
# connections it will hold on the handful of server connections above.
max_client_conn = 1000

# Protocol-level prepared statements survive transaction pooling from
# pgbouncer 1.21. Without this, every client library that prepares (which is
# most of them) errors on its second query.
max_prepared_statements = 200

# Logging to stderr, because the platform collects a process's stderr and a log
# file inside a guest is a log nobody reads.
logfile =
pidfile =
admin_users = postgres
EOF

exec pgbouncer /etc/pgbouncer/pgbouncer.ini
`

// What runs, by role. One entrypoint, three answers.
//
// The role is read at START, not baked in, so converting a database changes an
// environment variable rather than an image. A machine that comes back after a
// conversion is the same machine with a different process set.
const roleDispatch = `#!/bin/sh
set -e
case "${PILOT_PG_ROLE:-single}" in
  single)
    # What pilot add writes. Postgres on 5432, pgbouncer on 6432, nothing
    # else running and nothing else to go wrong.
    exec /usr/local/bin/pilot-entrypoint.sh "$@"
    ;;
  data)
    # Patroni OWNS postgres here: it starts it, it configures it, and it
    # decides when this node is primary. Starting postgres beside Patroni
    # would be two things managing one data directory.
    exec /usr/local/bin/pilot-patroni.sh
    ;;
  etcd)
    exec /usr/local/bin/pilot-etcd.sh
    ;;
  *)
    echo "pilot: unknown PILOT_PG_ROLE '$PILOT_PG_ROLE'" >&2
    exit 1
    ;;
esac
`

// Patroni's configuration, rendered at start from the environment.
//
// Rendered rather than shipped, because three of its values are per machine
// and one is a password: the node name, the addresses it advertises, the etcd
// cluster it joins, and the replication credential. A config file in the image
// would have to be templated at start anyway, and a password in an image is a
// password in every copy of it.
//
// `name` is $HOSTNAME, which is the MACHINE name and is stable across a
// redeploy. That matters more than it looks: Patroni identifies a member by
// name, so a node whose name changed on every deploy would join as a new
// member every time and leave the old one in the cluster for ever.
const patroniStart = `#!/bin/sh
set -e

: "${PILOT_ETCD_HOSTS:?PILOT_ETCD_HOSTS is required in data role}"
: "${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is required}"
SCOPE="${PILOT_PG_SCOPE:-pilots}"
NODE="${HOSTNAME}"
DATA="${PGDATA:-/var/lib/postgresql/data}"

mkdir -p "$DATA" /etc/patroni
chown -R postgres:postgres "$DATA"
chmod 700 "$DATA"

umask 077
cat > /etc/patroni/patroni.yml <<EOF
scope: ${SCOPE}
name: ${NODE}

restapi:
  # 0.0.0.0 because HAProxy on every OTHER node health-checks this one. The
  # guest firewall is what keeps that inside the app.
  listen: 0.0.0.0:8008
  connect_address: ${NODE}.internal:8008

etcd3:
  hosts: ${PILOT_ETCD_HOSTS}

bootstrap:
  dcs:
    # ttl 30 with loop_wait 10 gives a failover inside about half a minute,
    # and three loops of slack before a healthy leader is declared dead. A
    # shorter ttl trades real availability for a promotion on every hiccup.
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      parameters:
        wal_level: replica
        hot_standby: "on"
        max_wal_senders: 10
        max_replication_slots: 10
  initdb:
    - encoding: UTF8
    - data-checksums

postgresql:
  listen: 0.0.0.0:5432
  connect_address: ${NODE}.internal:5432
  data_dir: ${DATA}
  authentication:
    superuser:
      username: postgres
      password: "${POSTGRES_PASSWORD}"
    replication:
      username: replicator
      password: "${PATRONI_REPLICATION_PASSWORD:-$POSTGRES_PASSWORD}"
  # basebackup, because a new follower here has no local copy to rewind from:
  # the ordinal's volume is empty the first time it is used.
  create_replica_methods:
    - basebackup

tags:
  nofailover: false
  noloadbalance: false
  nosync: false
EOF
chown postgres:postgres /etc/patroni/patroni.yml

exec patroni /etc/patroni/patroni.yml
`

// HAProxy, following whichever node says it is primary.
//
// This is the whole reason no leader address is written anywhere: the check IS
// the source of truth, it is asked every second, and it cannot be stale in the
// way a replicated row would be exactly when a promotion happened.
//
// `server-template` with a DNS resolver rather than a fixed list, because the
// set of replicas changes with a scale and a fixed list would send traffic to a
// machine that no longer exists.
const haproxyStart = `#!/bin/sh
set -e
: "${PILOT_PG_SERVICE:?PILOT_PG_SERVICE is required in data role}"

mkdir -p /etc/haproxy
cat > /etc/haproxy/haproxy.cfg <<EOF
global
  maxconn 1000
defaults
  mode tcp
  timeout connect 5s
  timeout client 8h
  timeout server 8h

resolvers pilots
  nameserver gateway 169.254.0.22:53
  # One second, because a scale or a rescue changes what the name resolves to
  # and a stale answer here is traffic to a machine that is gone.
  hold valid 1s

frontend primary
  bind *:6432
  default_backend pg_primary

backend pg_primary
  option httpchk GET /primary
  http-check expect status 200
  # Every replica is a candidate and exactly one passes the check, so this is a
  # backend of N servers with N-1 always down. That is the design rather than a
  # misconfiguration: the check is what decides, every second.
  server-template pg 7 ${PILOT_PG_SERVICE}.internal:6433 check port 8008 resolvers pilots init-addr none inter 1s fall 2 rise 1
EOF

exec haproxy -f /etc/haproxy/haproxy.cfg -db
`

// One etcd member.
//
// Every member advertises itself by its MACHINE name, which is stable across a
// redeploy, and discovers the others through the service name. A member that
// renamed itself on every deploy would join as a new member and leave the old
// one in the cluster for ever, which is how a three-member quorum silently
// becomes a six-member cluster with three dead votes.
const etcdStart = `#!/bin/sh
set -e
: "${PILOT_ETCD_SERVICE:?PILOT_ETCD_SERVICE is required in etcd role}"
NODE="${HOSTNAME}"
DATA=/var/lib/etcd
mkdir -p "$DATA"

exec etcd \
  --name "$NODE" \
  --data-dir "$DATA" \
  --listen-client-urls http://0.0.0.0:2379 \
  --advertise-client-urls "http://${NODE}.internal:2379" \
  --listen-peer-urls http://0.0.0.0:2380 \
  --initial-advertise-peer-urls "http://${NODE}.internal:2380" \
  --discovery-srv-name "${PILOT_ETCD_SERVICE}" \
  --initial-cluster-state "${PILOT_ETCD_STATE:-new}" \
  --initial-cluster-token "${PILOT_ETCD_SERVICE}"
`

// Flushing the write-ahead log before a node is taken down.
//
// The 60-second archive timeout is the recovery point objective in ordinary
// running, and it is the right trade there. It is the WRONG trade at a moment
// we control: a conversion kills a node on purpose, and losing up to a minute
// of writes to a planned operation is a loss nobody agreed to.
//
// So the segment is switched and the archiver is waited on. Bounded, because a
// node that cannot archive must not hold a conversion open for ever; the
// caller decides what to do about a timeout, and it knows more than this
// script does.
const walFlush = `#!/bin/sh
set -e
DEADLINE=$(( $(date +%s) + 90 ))

WANT=$(psql -U postgres -Atqc "SELECT pg_walfile_name(pg_switch_wal())")
[ -n "$WANT" ] || { echo "pilot: could not switch the write-ahead log" >&2; exit 1; }

while [ "$(date +%s)" -lt "$DEADLINE" ]; do
  LAST=$(psql -U postgres -Atqc "SELECT coalesce(last_archived_wal, '') FROM pg_stat_archiver")
  # Lexical, because WAL segment names sort in the order they are written. A
  # last_archived_wal at or past the one we forced means ours is on the volume.
  if [ -n "$LAST" ] && [ ! "$LAST" \< "$WANT" ]; then
    echo "pilot: archived $LAST"
    exit 0
  fi
  sleep 1
done

echo "pilot: $WANT was not archived within 90s" >&2
exit 1
`
