// The anti-generated-design gate.
//
// The owner's hardest requirement for this site is that it must not look
// like a website generated by AI. AGENTS.md Part 1 states that as eleven
// invariants; this file is what stops them from being decoration.
//
// Prose in a doc does not survive the fourth agent to touch a file. A
// failing test does. When an invariant in AGENTS.md changes, change the
// matching rule here in the SAME commit, or the two drift and the document
// quietly becomes advisory.
//
// Scope: the files we author (app/, components/, modules/, lib/). The
// scaffold's demo gallery is already gone (`npm run gallery:clear`), so
// there is no vendored-fixture exemption to maintain.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readdirSync, readFileSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const APP_ROOT = fileURLToPath(new URL('../..', import.meta.url));
const SCANNED_DIRS = ['app', 'components', 'modules', 'lib'];

/** Every source file under the authored directories. */
function sourceFiles(): string[] {
  const out: string[] = [];
  const walk = (dir: string) => {
    let entries: string[];
    try {
      entries = readdirSync(dir);
    } catch {
      return; // a scanned dir may not exist yet
    }
    for (const entry of entries) {
      const full = join(dir, entry);
      if (statSync(full).isDirectory()) walk(full);
      else if (entry.endsWith('.ts') || entry.endsWith('.js')) out.push(full);
    }
  };
  for (const d of SCANNED_DIRS) walk(join(APP_ROOT, d));
  return out;
}

const FILES = sourceFiles().map((f) => ({ rel: relative(APP_ROOT, f), src: readFileSync(f, 'utf8') }));

/**
 * Source with comments removed.
 *
 * Comments must not be scanned. A comment that NAMES a banned word in order
 * to explain the rule (or a Tailwind class list in a utility's docs) is not
 * copy anyone reads, and flagging it makes the gate punish the act of
 * documenting itself. The `[^:]` guard keeps `https://` from being eaten as
 * a line comment.
 */
function stripComments(src: string): string {
  return src
    .replace(/\/\*[\s\S]*?\*\//g, ' ')
    .replace(/(^|[^:])\/\/.*$/gm, '$1');
}

/**
 * The MARKUP: the contents of html`` templates, tags and attributes intact.
 *
 * Class-name rules run on this rather than on the whole file, because a
 * banned utility class is only a design violation when it is applied to an
 * element. `lib/utils/cn.ts` is the counter-example that proved this: it
 * carries `bg-clip-text` as Tailwind class-group config data and contains no
 * markup at all, so scanning raw source flagged a file that renders nothing.
 *
 * The template match is deliberately shallow (it stops at the first
 * backtick), which can truncate a template containing a nested backtick.
 * That fails OPEN on the tail of such a template: a gate that occasionally
 * misses is fine, one that blocks a correct commit is not.
 */
function markupSource(src: string): string {
  return (stripComments(src).match(/html`[\s\S]*?`/g) ?? []).join('\n');
}

/**
 * The text a reader actually SEES: markup with tags, `${}` interpolations,
 * and sourced <data> elements removed.
 *
 * Scanning raw source instead would flag every `py-24` and every version
 * string, so the rules below that are about PROSE run on this.
 */
function visibleText(src: string): string {
  return markupSource(src)
    // A <script> in a template is CODE that happens to live in markup. Tag
    // stripping alone leaves its body behind as "text", and the punctuation
    // rule then reads the theme bootstrap's JavaScript semicolons as prose.
    // Same for <style>.
    .replace(/<script\b[\s\S]*?<\/script>/gi, ' ')
    .replace(/<style\b[\s\S]*?<\/style>/gi, ' ')
    .replace(/<data\b[^>]*>[\s\S]*?<\/data>/g, ' ') // sourced numbers are exempt, see rule 1
    .replace(/\$\{[\s\S]*?\}/g, ' ') // interpolated code is not prose
    .replace(/<[^>]+>/g, ' ') // tags, leaving text nodes
    // HTML entities are syntax, not punctuation. The semicolon terminating
    // `&rarr;` is not a semicolon a reader ever sees.
    .replace(/&[a-zA-Z]+;|&#\d+;/g, ' ');
}


/**
 * Everywhere a numeric claim can reach a reader.
 *
 * Markup alone is not enough, and finding that out was worth a rule change.
 * The roadmap page holds its phase gates ("under 500 milliseconds") in a plain
 * data array that html`` renders later, so scanning templates declared the
 * page clean while unsourced numbers sat on it. Anything a page can print has
 * to be scanned, not just the syntax it happens to print it with.
 *
 * So PROSE string literals are scanned too. Deciding what counts as prose is
 * the whole problem, and two false-positive families taught the rule:
 *
 *   class="${FOO} m-0 mb-2"     an attribute value INSIDE a template, read as
 *                               the literal " m-0 mb-2" and flagged as "0 mb"
 *   'public, max-age=60, …'     a Cache-Control header, flagged as "60, s"
 *
 * Both are fixed by the same observation: prose has SENTENCE punctuation and
 * configuration does not. Templates are removed first so attribute values are
 * never candidates, then a literal qualifies only if it contains a full stop
 * followed by a space or ending it. A Tailwind class list never does. A header
 * value never does. A sentence always does.
 */
function claimSurfaces(src: string): string[] {
  const out = [visibleText(src)];
  // Remove templates: their attribute values are markup, already covered.
  const bare = stripComments(src).replace(/html`[\s\S]*?`/g, ' ');
  for (const m of bare.matchAll(/'([^'\\\n]*)'|"([^"\\\n]*)"/g)) {
    const text = m[1] ?? m[2] ?? '';
    const isSentence = /\s/.test(text) && /[.!?](\s|$)/.test(text);
    if (isSentence) out.push(text);
  }
  return out;
}

// AGENTS.md invariant 5. Generated marketing prose reaches for these first.
const BANNED_WORDS = [
  'blazing fast', 'blazingly fast', 'seamlessly', 'seamless', 'effortlessly',
  'effortless', 'supercharge', 'unleash', 'elevate your', 'powerful yet simple',
  'the future of', 'game.changing', 'cutting.edge', 'best.in.class',
  'robust and scalable', 'lightning fast', 'take it to the next level',
  'join thousands', 'trusted by thousands',
];

test('invariant 5: no generated-marketing vocabulary', () => {
  const hits: string[] = [];
  for (const { rel, src } of FILES) {
    for (const word of BANNED_WORDS) {
      const m = new RegExp(word, 'i').exec(stripComments(src));
      if (m) hits.push(`${rel}: "${m[0]}"`);
    }
  }
  assert.deepEqual(hits, [], `Banned copy vocabulary (AGENTS.md invariant 5):\n${hits.join('\n')}`);
});

test('invariant 5: no three-word staccato tagline', () => {
  // "Fast. Secure. Simple." Three consecutive single-word sentences, each
  // capitalised. Reads as a tagline in every generated landing page and
  // essentially nowhere else.
  const hits: string[] = [];
  for (const { rel, src } of FILES) {
    const m = /\b([A-Z][a-z]+)\.\s+([A-Z][a-z]+)\.\s+([A-Z][a-z]+)\./.exec(visibleText(src));
    if (m) hits.push(`${rel}: "${m[0].trim()}"`);
  }
  assert.deepEqual(hits, [], `Staccato tagline (AGENTS.md invariant 5):\n${hits.join('\n')}`);
});

test('invariant 4: no gradient, blur-glass, or gradient-text utilities', () => {
  const BANNED_CLASSES = [
    /\bbg-gradient-to-[a-z]+\b/,
    /\bbg-linear-to-[a-z]+\b/, // tailwind v4 spelling
    /\bbackdrop-blur\b/,
    /\bbg-clip-text\b/,
  ];
  const hits: string[] = [];
  for (const { rel, src } of FILES) {
    for (const re of BANNED_CLASSES) {
      const m = re.exec(markupSource(src));
      if (m) hits.push(`${rel}: "${m[0]}"`);
    }
  }
  assert.deepEqual(hits, [], `Banned visual vocabulary (AGENTS.md invariant 4):\n${hits.join('\n')}`);
});

test('invariant 4: no emoji standing in for icons', () => {
  // Pictographic ranges only. Deliberately excludes the arrows and
  // punctuation blocks, so a real typographic arrow stays legal.
  const EMOJI = /[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}\u{FE0F}]/u;
  const hits: string[] = [];
  for (const { rel, src } of FILES) {
    const m = EMOJI.exec(visibleText(src));
    if (m) hits.push(`${rel}: ${JSON.stringify(m[0])}`);
  }
  assert.deepEqual(hits, [], `Emoji in rendered text (AGENTS.md invariant 4):\n${hits.join('\n')}`);
});

test('invariant 1: every measured claim carries provenance', () => {
  // A number with a unit, in text a reader sees, that is NOT inside a
  // <data data-source="..."> element. visibleText() has already stripped
  // those, so anything matching here is an unsourced claim.
  //
  // This is the rule that does the most work. "Sub-50ms" with nothing
  // behind it is the single loudest generated-copy tell, because it comes
  // from a process with no measurement in it.
  const CLAIM = /\b\d[\d,.]*\s?(ms|µs|s|x|%|GB|MB|TB|KB|×|milliseconds?|seconds?|minutes?)\b/i;
  const hits: string[] = [];
  for (const { rel, src } of FILES) {
    for (const text of claimSurfaces(src)) {
      const m = CLAIM.exec(text);
      if (m) hits.push(`${rel}: "${m[0]}", put it in lib/facts.ts and render it through #lib/ui/stat.ts`);
    }
  }
  assert.deepEqual(hits, [], `Unsourced numeric claim (AGENTS.md invariant 1):\n${hits.join('\n')}`);
});

test('invariant 11: theme colours are declared once, via light-dark()', () => {
  // A colour whose dark half is written twice (once under
  // prefers-color-scheme, once under the toggle attribute) drifts silently.
  // webjs.dev shipped that bug and had to fix it; the fix is light-dark().
  const hits: string[] = [];
  for (const { rel, src } of FILES) {
    const bare = stripComments(src);
    if (/prefers-color-scheme/.test(bare) && /\[data-theme/.test(bare)) {
      hits.push(`${rel}: declares colours under BOTH prefers-color-scheme and [data-theme]`);
    }
  }
  assert.deepEqual(hits, [], `Duplicated theme declaration (AGENTS.md invariant 11):\n${hits.join('\n')}`);
});

test('invariant 10: the domain is written in exactly one place', () => {
  const hits: string[] = [];
  for (const { rel, src } of FILES) {
    if (rel === join('lib', 'links.ts')) continue;
    if (/pilots\.run/.test(stripComments(src))) hits.push(`${rel}: hard-codes the domain; import it from #lib/links.ts`);
  }
  assert.deepEqual(hits, [], `Hard-coded domain (AGENTS.md invariant 10):\n${hits.join('\n')}`);
});

test('invariant 12: no kicker label stacked above a heading', () => {
  // The single most recognisable generated-page rhythm: a small label, then a
  // heading, then a lede, repeated down the page. Swapping the coloured pill
  // for a monospace uppercase label does NOT fix it, which is exactly the trap
  // this site fell into on its first pass: eighteen sections all opened with
  // the same three-part stack. The tell is the STACK, not the styling.
  //
  // Reference point: the webjs marketing site has zero of these on its home
  // page. Its only uppercase labels are footer column headings, which sit
  // above a LIST of links rather than above a heading, and are not this.
  //
  // A heading that needs a label above it to be understood needs rewriting,
  // which is why section() and pageHero() no longer accept an eyebrow at all.
  const KICKER = /<(p|span|div)\b[^>]*(FIELD_LABEL|uppercase)[^>]*>[\s\S]{0,200}?<\/\1>\s*<h[1-3]\b/;
  const hits: string[] = [];
  for (const { rel, src } of FILES) {
    if (KICKER.test(markupSource(src))) {
      hits.push(`${rel}: a small label sits directly above a heading`);
    }
  }
  assert.deepEqual(hits, [], `Kicker above a heading (AGENTS.md invariant 12):\n${hits.join('\n')}`);
});

test('invariant 13: prose punctuation', () => {
  // The house rule the sibling project already enforces with a commit hook:
  // no em-dash, and no space-surrounded hyphen or semicolon used as a pause
  // between words. Use a period, a comma, parentheses, or restructure.
  //
  // Scanned over the same surfaces as the numeric claim, so it covers prose
  // held in data arrays as well as prose in markup. Plain hyphens inside
  // compound words, flags, and filenames are untouched, and arithmetic like
  // `n - 1` is code rather than prose so it never reaches here.
  // The semicolon rule is ANY semicolon, not just a space-surrounded one.
  // The first version copied the sibling project's " ; " pattern and six
  // ordinary "word; word" semicolons sailed straight past it, including one in
  // a page description that search engines render. Prose here uses a period or
  // a comma. Code is unaffected: this runs on rendered text and sentence-shaped
  // string literals, so a TypeScript member separator never reaches it.
  const RULES: [RegExp, string][] = [
    [/\u2014/, 'em-dash'],
    [/;/, 'semicolon'],
    [/\s-\s/, 'hyphen used as a pause'],
  ];
  const hits: string[] = [];
  for (const { rel, src } of FILES) {
    for (const text of claimSurfaces(src)) {
      for (const [re, name] of RULES) {
        if (re.test(text)) hits.push(`${rel}: ${name}`);
      }
    }
  }
  assert.deepEqual([...new Set(hits)], [], `Prose punctuation (AGENTS.md invariant 13):\n${hits.join('\n')}`);
});
