"""``pilots.adk`` -- Google ADK plugin: a pilots machine as an agent's tools.

    pip install 'pilots-sdk[adk]'

    from google.adk.agents import Agent
    from pilots.adk import PilotsPlugin

    plugin = PilotsPlugin()  # or PilotsPlugin(machine_name="my-project")
    agent = Agent(model="gemini-flash-latest", name="pilot_agent",
                  instruction="Run code and commands in the pilots machine, not locally.",
                  tools=plugin.get_tools())

Two modes. ``PilotsPlugin()`` generates an ``adk-`` prefixed name and destroys
the machine on ``close()``. ``PilotsPlugin(machine_name="…")`` reuses a named
machine, whose filesystem, packages and services survive between sessions, and
never destroys it.

The machine is created lazily on first tool use, so constructing the agent
needs no network. Every tool returns a structured dict -- ``success`` plus
``stdout``/``stderr``/``exit_code`` or ``error`` -- so a failure lets the model
adapt instead of crashing the run.

File reads and writes run as commands inside the machine (via base64, so
quotes, newlines and unicode survive) rather than through a separate
filesystem API. That keeps them consistent with everything else the agent does
and, in particular, correctly reverted by ``restore_machine_checkpoint``.
"""

from __future__ import annotations

import asyncio
import base64
import logging
import threading
import uuid
from typing import TYPE_CHECKING, Any

from .client import PilotsClient
from .errors import NotFoundError, PilotsError
from .types import Machine

if TYPE_CHECKING:  # pragma: no cover - typing only
    from google.adk.plugins.base_plugin import BasePlugin
    from google.adk.tools.base_tool import BaseTool

logger = logging.getLogger("pilots.adk")

#: A write larger than this should be generated by a command inside the
#: machine: a base64 argv that big is a shell the guest will refuse.
MAX_WRITE_BYTES = 256 * 1024

TOOL_NAMES = [
    "execute_command_in_machine",
    "execute_code_in_machine",
    "write_file_to_machine",
    "read_file_from_machine",
    "create_machine_checkpoint",
    "list_machine_checkpoints",
    "restore_machine_checkpoint",
]


def _quote(s: str) -> str:
    return "'" + s.replace("'", "'\\''") + "'"


class MachineSession:
    """The lifecycle half, importable without ADK installed: get-or-create a
    machine, run things in it, tear it down. ``PilotsPlugin`` wraps it with
    ADK's tool objects, and the tests drive this directly."""

    def __init__(
        self,
        api_key: str | None = None,
        machine_name: str | None = None,
        *,
        base_url: str | None = None,
        destroy_on_close: bool | None = None,
        client_timeout: float = 600.0,
        client: PilotsClient | None = None,
    ) -> None:
        if machine_name:
            self.machine_name = machine_name
            self._destroy_on_close = bool(destroy_on_close) if destroy_on_close is not None else False
        else:
            self.machine_name = f"adk-{uuid.uuid4().hex[:8]}"
            self._destroy_on_close = True if destroy_on_close is None else bool(destroy_on_close)
        self._client = client or PilotsClient(api_key, base_url=base_url, timeout=client_timeout)
        self._machine: Machine | None = None
        self._lock = threading.Lock()

    # -- lifecycle -------------------------------------------------------------

    def get_machine(self) -> Machine:
        """The managed machine, created on first use. Thread-safe: ADK runs
        tool calls in worker threads."""
        with self._lock:
            if self._machine is None:
                self._machine = self._find() or self._client.machines.create(name=self.machine_name)
            return self._machine

    def _find(self) -> Machine | None:
        try:
            for m in self._client.machines.list():
                if m.name == self.machine_name:
                    logger.info("reusing machine %r", self.machine_name)
                    return m
        except PilotsError:
            return None
        return None

    def destroy(self) -> None:
        """Destroy the machine and all of its state. Irreversible."""
        with self._lock:
            try:
                if self._machine is not None:
                    self._client.machines.destroy(self._machine.id)
            except NotFoundError:
                pass
            self._machine = None

    async def close(self) -> None:
        if self._destroy_on_close:
            await asyncio.to_thread(self.destroy)
        await asyncio.to_thread(self._client.close)

    # -- the seven tools ---------------------------------------------------------

    def execute_command(self, command: str, cwd: str | None = None, timeout: float | None = None) -> dict[str, Any]:
        try:
            m = self.get_machine()
            res = self._client.machines.exec(
                m.id, cmd=command, cwd=cwd, timeout_ms=int(timeout * 1000) if timeout else None
            )
            return {"success": res.exit_code == 0, "stdout": res.stdout, "stderr": res.stderr,
                    "exit_code": res.exit_code, "machine": m.name}
        except PilotsError as err:
            return {"success": False, "error": str(err), "code": err.code, "next": err.next}

    def execute_code(self, code: str, language: str = "python") -> dict[str, Any]:
        runners = {
            "python": "python3 -",
            "python3": "python3 -",
            "javascript": "node -",
            "node": "node -",
            "bash": "bash -s",
            "sh": "sh -s",
        }
        runner = runners.get(language.lower())
        if runner is None:
            return {"success": False, "error": f"unsupported language {language!r}; use {', '.join(sorted(set(runners)))}"}
        encoded = base64.b64encode(code.encode()).decode()
        return self.execute_command(f"printf %s {_quote(encoded)} | base64 -d | {runner}")

    def write_file(self, path: str, content: str) -> dict[str, Any]:
        if len(content.encode()) > MAX_WRITE_BYTES:
            return {
                "success": False,
                "error": f"content is larger than {MAX_WRITE_BYTES} bytes; "
                         "generate it with a command inside the machine",
            }
        encoded = base64.b64encode(content.encode()).decode()
        res = self.execute_command(
            f"mkdir -p -- $(dirname {_quote(path)}) && printf %s {_quote(encoded)} | base64 -d > {_quote(path)}"
        )
        if res.get("success"):
            return {"success": True, "path": path, "bytes": len(content.encode())}
        return res

    def read_file(self, path: str) -> dict[str, Any]:
        res = self.execute_command(f"base64 -w0 -- {_quote(path)}")
        if not res.get("success"):
            why = (res.get("stderr") or res.get("error") or "").strip()
            return {"success": False, "error": why or f"cannot read {path}"}
        try:
            return {"success": True, "path": path, "content": base64.b64decode(res["stdout"]).decode()}
        except Exception as err:  # binary, or a truncated read
            return {"success": False, "error": f"{path} is not text: {err}"}

    def create_checkpoint(self, comment: str = "") -> dict[str, Any]:
        try:
            m = self.get_machine()
            ck = self._client.machines.checkpoint(m.id, comment or None)
            return {"success": True, "checkpoint_id": ck.id, "comment": ck.comment or "", "created_at": ck.created_at}
        except PilotsError as err:
            return {"success": False, "error": str(err), "code": err.code, "next": err.next}

    def list_checkpoints(self) -> dict[str, Any]:
        try:
            m = self.get_machine()
            found: list[Any] = list(self._client.machines.list_checkpoints(m.id))
            checkpoints = sorted(found, key=lambda c: c.created_at, reverse=True)
            return {"success": True, "checkpoints": [
                {"checkpoint_id": c.id, "comment": c.comment or "", "created_at": c.created_at, "durable": c.durable}
                for c in checkpoints
            ]}
        except PilotsError as err:
            return {"success": False, "error": str(err), "code": err.code, "next": err.next}

    def restore_checkpoint(self, checkpoint_id: str, confirm: bool = False) -> dict[str, Any]:
        """Rewinds the WHOLE machine and permanently discards anything newer
        than the checkpoint. Refuses without ``confirm=True``."""
        if not confirm:
            return {"success": False,
                    "error": "restoring discards every change made after the checkpoint; "
                             "get the user's explicit confirmation, then call again with confirm=true"}
        try:
            self._machine = self._client.checkpoints.restore(checkpoint_id)
            return {"success": True, "checkpoint_id": checkpoint_id, "machine": self._machine.name,
                    "note": "restored in place: same machine, same URL"}
        except PilotsError as err:
            return {"success": False, "error": str(err), "code": err.code, "next": err.next}


def _tool_specs(session: MachineSession) -> list[tuple[str, str, dict[str, Any], Any]]:
    """(name, description, JSON-schema properties, handler) for each tool."""
    return [
        (
            "execute_command_in_machine",
            "Run a shell command inside the pilots machine and return stdout, stderr and the exit code. "
            "A non-zero exit is a result, not an error: read it and decide.",
            {
                "command": {"type": "string", "description": "the shell command to run"},
                "cwd": {"type": "string", "description": "working directory; defaults to the login directory"},
                "timeout": {"type": "number", "description": "seconds before the command is killed"},
            },
            lambda args: session.execute_command(args["command"], args.get("cwd"), args.get("timeout")),
        ),
        (
            "execute_code_in_machine",
            "Run a Python, JavaScript or bash snippet inside the pilots machine. The code is piped to the "
            "interpreter, so it needs no file on disk.",
            {
                "code": {"type": "string", "description": "the source to run"},
                "language": {"type": "string", "description": "python, javascript or bash", "default": "python"},
            },
            lambda args: session.execute_code(args["code"], args.get("language", "python")),
        ),
        (
            "write_file_to_machine",
            f"Write a text file inside the pilots machine, creating parent directories. Capped at "
            f"{MAX_WRITE_BYTES // 1024} KB; generate anything larger with a command inside the machine.",
            {
                "path": {"type": "string", "description": "absolute path inside the machine"},
                "content": {"type": "string", "description": "the file's text"},
            },
            lambda args: session.write_file(args["path"], args["content"]),
        ),
        (
            "read_file_from_machine",
            "Read a text file from inside the pilots machine.",
            {"path": {"type": "string", "description": "absolute path inside the machine"}},
            lambda args: session.read_file(args["path"]),
        ),
        (
            "create_machine_checkpoint",
            "Snapshot the entire machine, memory included, so it can be restored to this exact moment. "
            "Do this before a package upgrade, a migration, or any command you cannot undo.",
            {"comment": {"type": "string", "description": "what this checkpoint is for"}},
            lambda args: session.create_checkpoint(args.get("comment", "")),
        ),
        (
            "list_machine_checkpoints",
            "List the machine's checkpoints, newest first.",
            {},
            lambda args: session.list_checkpoints(),
        ),
        (
            "restore_machine_checkpoint",
            "DESTRUCTIVE. Roll the whole machine back to a checkpoint, discarding every change made after it. "
            "Ask the user to confirm in words first, then call this with confirm=true.",
            {
                "checkpoint_id": {
                    "type": "string",
                    "description": "from create_machine_checkpoint or list_machine_checkpoints",
                },
                "confirm": {"type": "boolean", "description": "must be true; the user has to agree first"},
            },
            lambda args: session.restore_checkpoint(args["checkpoint_id"], bool(args.get("confirm"))),
        ),
    ]


#: JSON-schema type names to the ADK enum members that carry them.
_SCHEMA_TYPES = {"string": "STRING", "number": "NUMBER", "boolean": "BOOLEAN"}


def _build_tools(session: MachineSession) -> list[BaseTool]:
    from google.adk.tools.base_tool import BaseTool
    from google.genai import types as genai_types

    class _MachineTool(BaseTool):
        def __init__(self, name: str, description: str, properties: dict[str, Any], handler: Any) -> None:
            super().__init__(name=name, description=description)
            self._properties = properties
            self._handler = handler

        def _get_declaration(self) -> Any:
            optional = ("cwd", "timeout", "comment")
            required = [
                k for k, v in self._properties.items() if "default" not in v and k not in optional
            ]
            return genai_types.FunctionDeclaration(
                name=self.name,
                description=self.description,
                parameters=genai_types.Schema(
                    type=genai_types.Type.OBJECT,
                    properties={
                        k: genai_types.Schema(
                            type=getattr(genai_types.Type, _SCHEMA_TYPES[v["type"]]),
                            description=v.get("description", ""),
                        )
                        for k, v in self._properties.items()
                    },
                    required=required,
                ),
            )

        async def run_async(self, *, args: dict[str, Any], tool_context: Any) -> dict[str, Any]:
            return await asyncio.to_thread(self._handler, args)

    return [_MachineTool(name, desc, props, handler) for name, desc, props, handler in _tool_specs(session)]


class PilotsPlugin:
    """The ADK plugin. Pass ``plugin.get_tools()`` to an ``Agent`` and the
    plugin itself to the runner for lifecycle callbacks."""

    def __init__(
        self,
        api_key: str | None = None,
        machine_name: str | None = None,
        *,
        plugin_name: str = "pilots_plugin",
        base_url: str | None = None,
        destroy_on_close: bool | None = None,
        client_timeout: float = 600.0,
    ) -> None:
        self.session = MachineSession(
            api_key,
            machine_name,
            base_url=base_url,
            destroy_on_close=destroy_on_close,
            client_timeout=client_timeout,
        )
        self.plugin_name = plugin_name
        self._tools: list[Any] | None = None
        self._base: Any | None = None

    @property
    def machine_name(self) -> str:
        return self.session.machine_name

    def get_tools(self) -> list[Any]:
        """The tools to hand an ADK ``Agent``. Importing ADK is deferred to
        here, so constructing the plugin does not require the extra."""
        if self._tools is None:
            self._tools = _build_tools(self.session)
        return list(self._tools)

    def as_plugin(self) -> BasePlugin:
        """The object a runner takes in ``plugins=[…]``."""
        from google.adk.plugins.base_plugin import BasePlugin

        if self._base is None:
            outer = self

            class _Plugin(BasePlugin):
                def __init__(self) -> None:
                    super().__init__(name=outer.plugin_name)

                async def on_user_message_callback(self, **_: Any) -> None:
                    return None

            self._base = _Plugin()
        return self._base

    async def close(self) -> None:
        await self.session.close()


__all__ = ["PilotsPlugin", "MachineSession", "TOOL_NAMES", "MAX_WRITE_BYTES"]
