import { chromium } from 'playwright';
import { writeFileSync } from 'node:fs';
const SP = process.argv[2];
const b = await chromium.launch();
const p = await b.newPage({ viewportSize: { width: 1400, height: 900 }, deviceScaleFactor: 2 });
await p.goto('http://localhost:8123/logo-lab', { waitUntil: 'domcontentloaded' });
await p.waitForTimeout(1200);
const card = p.locator('article').filter({ has: p.locator('h3:text-is("Turned, no stem half full")') }).first();
await card.locator('.lab-dark').first().screenshot({ path: `${SP}/full.png` });
await b.close();
