#!/usr/bin/env python3
"""Regenerate lib/design/wordmark-outlines.ts.

The wordmark's letters ship as OUTLINES rather than as live text. This site
sets its type in a system font stack, so a wordmark set in `ui-sans-serif`
renders as a different typeface on macOS, on Windows and on Linux, which is the
opposite of a brand. As paths it is one drawing everywhere, needs no font
shipped beside it, and survives being pasted into a README or a design tool.

The face is Inter Tight, licensed under the SIL Open Font License 1.1, which
permits converting glyphs to outlines and using the result in a logo. Only the
six letters of the name are extracted; no font file is vendored into this repo.

Requires fonttools and brotli, neither of which is a project dependency:

    python3 -m venv /tmp/fontenv && /tmp/fontenv/bin/pip install fonttools brotli
    /tmp/fontenv/bin/python apps/website/scripts/build-wordmark-outlines.py <font.woff2>

Emitted on the lockup's grid: cap height 100, baseline y=100, y growing
downward, the first glyph starting at x=0, so the drawing in wordmark.ts can
place the mark against the letters without rescaling anything.
"""
import sys, pathlib
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen

CAP = 100.0
OUT = pathlib.Path(__file__).resolve().parents[1] / 'lib' / 'design' / 'wordmark-outlines.ts'

def outlines(font_path, word, weight, tracking_em):
    f = instancer.instantiateVariableFont(TTFont(font_path), {'wght': weight})
    upem = f['head'].unitsPerEm
    s = CAP / f['OS/2'].sCapHeight
    gs, cmap, hmtx = f.getGlyphSet(), f.getBestCmap(), f['hmtx']
    track = tracking_em * upem * s
    x, glyphs = 0.0, []
    for ch in word:
        pen = SVGPathPen(gs, ntos=lambda v: f"{v:.2f}")
        # x' = s*x + offset ; y' = -s*y + CAP, so the baseline lands on y = CAP.
        gs[cmap[ord(ch)]].draw(TransformPen(pen, (s, 0, 0, -s, x, CAP)))
        adv = hmtx[cmap[ord(ch)]][0] * s
        glyphs.append({'ch': ch, 'd': pen.getCommands(), 'x': round(x, 2), 'adv': round(adv, 2)})
        x += adv + track
    return {'width': round(x - track, 2), 'glyphs': glyphs}

SETS = [
    ('PILOTS_MIXED', 'Pilots', 800, 0.005),
    ('PILOTS_UPPER', 'PILOTS', 800, 0.09),
    ('PILOTS_DOTLESS', 'Pılots', 800, 0.005),
]

def main(font_path):
    out = [__doc__.split('\n\n')[0], '']
    out = ['/**', ' * GENERATED by scripts/build-wordmark-outlines.py. Do not hand-edit.', ' *',
           ' * Inter Tight (SIL Open Font License 1.1) with its weight axis instanced, the',
           ' * six letters of the name converted to outlines. Cap height 100, baseline',
           ' * y = 100, y growing downward, first glyph at x = 0.',
           ' *',
           ' * Outlines rather than live text: this site sets its type in a system stack, so',
           ' * a wordmark set in `ui-sans-serif` would be a different typeface on every',
           ' * operating system. As paths it is one drawing everywhere.',
           ' */', '']
    for name, word, wt, tr in SETS:
        o = outlines(font_path, word, wt, tr)
        out.append(f"/** {word!r} at weight {wt}, tracking {tr}em. */")
        out.append(f"export const {name}_W = {o['width']};")
        out.append(f"export const {name}_D =\n  '{' '.join(g['d'] for g in o['glyphs'])}';")
        out.append('')
    gi = [g for g in outlines(font_path, 'Pılots', 800, 0.005)['glyphs'] if g['ch'] == 'ı'][0]
    out.append("/** The dotless i's slot, so a tittle is placed rather than guessed. */")
    out.append(f"export const DOTLESS_I_X = {gi['x']};")
    out.append(f"export const DOTLESS_I_ADV = {gi['adv']};")
    OUT.write_text('\n'.join(out) + '\n')
    print(f"wrote {OUT}")

if __name__ == '__main__':
    main(sys.argv[1])
