package volumes

import (
	"context"
	"fmt"
	"os"
	"strings"
)

// Litestream keeps each volume's SQLite metadata database durable in object
// storage, which is what lets the volume be mounted somewhere else after its
// host dies. Without it the metadata lives on exactly one machine's disk and
// the volume's chunks in the bucket are unreadable rubble.
//
// It runs under systemd as litestream@<vol-id>.service rather than as a child
// of hostd, because it has to outlive a hostd restart and a host reboot for
// the same reason the machines do: the durability it provides is not a
// property of whether the daemon happens to be up.

// UnitFor is the systemd unit that replicates one volume's metadata.
func UnitFor(id string) string { return "litestream@" + id + ".service" }

// litestreamConfig renders the per-volume configuration.
//
// The credentials go in the file rather than the unit's environment because
// the unit is a shared template and the file is per volume; it is written 0600
// and sits beside /etc/pilots/config, which already holds the same secret in
// the same trust class.
//
// force-path-style, like everywhere else: the fleet's object store does not
// serve virtual-host style addressing.
func (m *Manager) litestreamConfig(id string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by hostd for volume %s. Do not edit.\n", id)
	fmt.Fprintf(&b, "dbs:\n")
	fmt.Fprintf(&b, "  - path: %s\n", m.MetaPath(id))
	fmt.Fprintf(&b, "    replicas:\n")
	fmt.Fprintf(&b, "      - type: s3\n")
	fmt.Fprintf(&b, "        bucket: %s\n", m.cfg.Bucket)
	fmt.Fprintf(&b, "        path: %s\n", metaReplicaPath(id))
	fmt.Fprintf(&b, "        endpoint: %s\n", m.cfg.Endpoint)
	fmt.Fprintf(&b, "        region: %s\n", m.cfg.Region)
	fmt.Fprintf(&b, "        force-path-style: true\n")
	fmt.Fprintf(&b, "        access-key-id: %s\n", m.cfg.AccessKey)
	fmt.Fprintf(&b, "        secret-access-key: %s\n", m.cfg.SecretKey)
	return b.String()
}

// writeConfig puts the volume's Litestream configuration in place.
func (m *Manager) writeConfig(id string) error {
	if err := os.MkdirAll(m.cfg.ConfigRoot, 0o700); err != nil {
		return fmt.Errorf("volumes: mkdir %s: %w", m.cfg.ConfigRoot, err)
	}
	// 0600: it carries the bucket credentials.
	if err := os.WriteFile(m.ConfigPath(id), []byte(m.litestreamConfig(id)), 0o600); err != nil {
		return fmt.Errorf("volumes: write litestream config for %s: %w", id, err)
	}
	return nil
}

// startReplication brings up the volume's Litestream unit.
func (m *Manager) startReplication(ctx context.Context, id string) error {
	if _, err := m.run(ctx, "systemctl", "enable", "--now", UnitFor(id)); err != nil {
		return fmt.Errorf("volumes: start replication for %s: %w", id, err)
	}
	return nil
}

// stopReplication stops it, which is what a move does before handing the
// volume on.
func (m *Manager) stopReplication(ctx context.Context, id string) error {
	if _, err := m.run(ctx, "systemctl", "disable", "--now", UnitFor(id)); err != nil {
		return fmt.Errorf("volumes: stop replication for %s: %w", id, err)
	}
	return nil
}

// restoreMeta pulls the metadata database back from object storage.
//
// This runs BEFORE the mount on any host that is taking a volume over, and the
// order is the whole of landmine 5. A host that mounts against a local meta.db
// it happens to still have -- a stale one from an earlier lifetime, or an
// empty one it just created -- writes into a filesystem whose metadata
// disagrees with the chunks in object storage. Nothing errors; the volume
// simply comes back missing whatever the other host wrote last.
//
// -if-replica-exists so that the very first mount after a create, when there
// is nothing to restore yet, is not an error.
func (m *Manager) restoreMeta(ctx context.Context, id string) error {
	if _, err := os.Stat(m.MetaPath(id)); err == nil {
		// A restore refuses to overwrite an existing database, and the
		// existing one is exactly what must not be trusted here.
		if err := os.Remove(m.MetaPath(id)); err != nil {
			return fmt.Errorf("volumes: discard the stale metadata for %s: %w", id, err)
		}
	}
	if _, err := m.run(ctx, m.cfg.LitestreamBin, "restore",
		"-if-replica-exists", "-config", m.ConfigPath(id), m.MetaPath(id)); err != nil {
		return fmt.Errorf("volumes: restore metadata for %s: %w", id, err)
	}
	return nil
}
